// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradeViewer.Infrastructure.Persistence;

#nullable disable

namespace TradeViewer.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("TradeViewer.Domain.Entities.Trade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CapitalGainsPnl")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("Commission")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("ExitPrice")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("FifoPnlRealized")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("FxPnl")
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NetCash")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("NetCashInBase")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("PnL")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime?>("ReportDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TradeDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TradeDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("TradeId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TradeMoney")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Trades");
                });
#pragma warning restore 612, 618
        }
    }
}
